// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../src/domain/models/note_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6686837588287159165),
      name: 'NoteModel',
      lastPropertyId: const IdUid(6, 883170223167135406),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6725798941655681403),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6682683997998105852),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3467408965488745862),
            name: 'note',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 2028551929685813334),
            name: 'color',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 734207400363431009),
            name: 'time',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 883170223167135406),
            name: 'favorite',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 6686837588287159165),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    NoteModel: EntityDefinition<NoteModel>(
        model: _entities[0],
        toOneRelations: (NoteModel object) => [],
        toManyRelations: (NoteModel object) => {},
        getId: (NoteModel object) => object.id,
        setId: (NoteModel object, int id) {
          object.id = id;
        },
        objectToFB: (NoteModel object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final noteOffset = fbb.writeString(object.note);
          fbb.startTable(7);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, noteOffset);
          fbb.addInt64(3, object.color);
          fbb.addInt64(4, object.time.millisecondsSinceEpoch);
          fbb.addBool(5, object.favorite);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = NoteModel(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              title: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              note: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              color:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              favorite: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 14, false),
              time: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [NoteModel] entity fields to define ObjectBox queries.
class NoteModel_ {
  /// see [NoteModel.id]
  static final id = QueryIntegerProperty<NoteModel>(_entities[0].properties[0]);

  /// see [NoteModel.title]
  static final title =
      QueryStringProperty<NoteModel>(_entities[0].properties[1]);

  /// see [NoteModel.note]
  static final note =
      QueryStringProperty<NoteModel>(_entities[0].properties[2]);

  /// see [NoteModel.color]
  static final color =
      QueryIntegerProperty<NoteModel>(_entities[0].properties[3]);

  /// see [NoteModel.time]
  static final time =
      QueryIntegerProperty<NoteModel>(_entities[0].properties[4]);

  /// see [NoteModel.favorite]
  static final favorite =
      QueryBooleanProperty<NoteModel>(_entities[0].properties[5]);
}
